### ISSUE TITLE
EventChannel의 Stream은 어떻게 관리해야할까?

### ISSUE THREAD

**Issue by Soogyo-In** [flutterstudygn/archive#1]
Flutter를 하다보면 필연적으로 EventChannel을 사용하게된다.

EventChannel에 대해 잘 모르는 사람들이 있다면 쉽게말해 Platform간의 event를 listening하는 channel이다. 그러면서 값을 전달하는데 이를 Dart에선 Stream으로 받아온다.

EventChannel과 Stream이 뭔지 모른다면 일단 공식 문서를 추천한다.
영어라서 부담된다면 구글에서 검색하여 검색창 밑 도구를 눌러 모든 언어 -> 한국어를 선택하여 위에 나오는 3개 정도 읽으면 이해되지 않을가 싶다.
링크를 걸지 않는 이유는 해당 페이지가 사라질지도 모르며 업데이트로 인해 내용이 바뀔지도 모르기 때문이다. 뭐 상기의 자료 수집 정도는 쉽지 않은가?

서론은 이정도에서 마무리하고 본론인 EventChannel의 Stream은 어떻게 관리해야할까? 라는 주제로 넘어가자.

Flutter에서 EventChannel을 쓰는 대표적인 경우가 어떤 것일까?라는 질문이 무색하게 경험담으로 풀어가겠다.
필자는 위치 기반 서비스에 종사하고있기에 기기의 GPS값과 방위를 수신하는데 썼다.
[기기 방위각을 받아오는 plugin](https://github.com/SugyoIn-LBSTech/flutter_sensors)(필자가 작업해서 pub 페이지가 없다.)
[기기 GPS를 받아오는 plugin](https://pub.dev/packages/location)

자 위의 경우를 UI에 반영한다고 생각해보자.(필자의 경험 그대로를 따라가고 있다)
상황은 이렇다. 무엇이 되었건 사용자 기기 주변의 지정학적 점들의 사용자 위치기준 방향을 화살표로 ListView에 보여주고 item을 터치시 새로이 Widget을 push해 사용자 기준 해당 점까지의 방향을 화살표로 표시한다고 하자.
이를 구현하기 위해선 세가지 데이터가 필요하다. 첫번째는 목표점의 좌표, 두번째는 사용자 기기의 좌표, 세번째는 사용자 기기가 향하고있는 방위이다.
여기서 첫번째 데이터는 어떠한 경로로 얻어온다하고. 두,세번째 데이터는 기기에서 얻어와야한다. 여기에서 위에 소개한 두 개의 plugin을 사용한다.

자 필자가 사용한 첫번째 방법이다.
주변 점들까지의 방향을 표시하는 PointListPage가 있다. 점들에 대한 방향을 표시하고 싶기에 StreamBuilder의 stream으로 위 두 plugin의 값을 받아와 표시한다. 
그리고 해당 리스트의 특정 아이템을 선택하면 보여지는 PointPage가 있다. 여기서도 마찬가지로 StreamBuilder의 stream으로 위 두 plugin의 값을 받아와 표시한다. 쉽네?
하지만 문제는 여기서 발생한다. 무려 세가지나.

1. StreamBuilder는 내부적으로 자신이 dispose될 때 listening하고있는 stream을 cancel한다.
```

class _StreamBuilderBaseState<T, S> extends State<StreamBuilderBase<T, S>> {

  ...

  StreamSubscription<T> _subscription;

  @override
  void dispose() {
    _unsubscribe();
    super.dispose();
  }

  void _subscribe() {
    if (widget.stream != null) {
      _subscription = widget.stream.listen((T data) {
        setState(() {
          _summary = widget.afterData(_summary, data);
        });
      }, onError: (Object error) {
        setState(() {
          _summary = widget.afterError(_summary, error);
        });
      }, onDone: () {
        setState(() {
          _summary = widget.afterDone(_summary);
        });
      });
      _summary = widget.afterConnected(_summary);
    }
  }

  void _unsubscribe() {
    if (_subscription != null) {
      _subscription.cancel();
      _subscription = null;
    }
  }

  ...

```

2. EventChannel은 새로운 Listener가 들어오면 이전 listener를 없에버리고 새로운 listener를 가진다. 즉 데이터 제공 대상을 하나만 가진다. 쉽게 말하자면 A에게 데이터를 주다가 B가 달라하면 B에게만 주고 A는 잊는다. 
```
public final class EventChannel {
    
    ...

    private final class IncomingStreamRequestHandler implements BinaryMessageHandler {

        ....

        private void onListen(Object arguments, BinaryReply callback) {
            final EventSink eventSink = new EventSinkImplementation();
            final EventSink oldSink = activeSink.getAndSet(eventSink);
            if (oldSink != null) {
              // Repeated calls to onListen may happen during hot restart.
              // We separate them with a call to onCancel.
              try {
                  handler.onCancel(null);
              } catch (RuntimeException e) {
                  Log.e(TAG + name, "Failed to close existing event stream", e);
              }
            }
            try {
                handler.onListen(arguments, eventSink);
                callback.reply(codec.encodeSuccessEnvelope(null));
            } catch (RuntimeException e) {
                activeSink.set(null);
                Log.e(TAG + name, "Failed to open event stream", e);
                callback.reply(codec.encodeErrorEnvelope("error", e.getMessage(), null));
            }
        }

        ....

    }

    ....

}
```

3. Flutter의 Widget은 Android와 같은 생명 주기를 가지고 있지 않다.\
말 그대로다. 필자가IOS는 경험해보지 못하여 Android밖에 말을 못하지만 IOS와도 다를 것이다. 
문제가 됐던 부분은 (안드로이드 기준) onPaused가 없다는 것이다. 누군가는 WidgetBindingObserver에 있다고 할 수 있다. 하지만 굉장히 큰 차이가 존재한다.  바로 단위가 Activity가 아니라 App자체 이기 때문이다. 본래 Android에선 다른 ActiviryB가 ActivityA의 일부라도 가리면 ActivityA는 onPaused로 빠지게 된다. 하지만 Flutter에션 App자체가 background로 가야 Widget이 onPause로 빠진다는 것이다. 그러다보니 WidgetB가 WidgetA를 덮었을 때의 callback이 없다.

자 일단은 여기까지만 하고 글을 줄이도록 하겠다. 이미 막걸리 두 병을 마셨고 지금까지 쓴 글을 날릴까 무섭기 때문이다ㅎㅎ

자 다음은 이런 경우 무슨 일이 벌어질까?이다.
당연히 빡치는 일이 발생한다.

**Comment by Deockyoung** [comment]
좋은글 감사합니다..
stream 얼렁 사용해보고 다시한번 읽어봐야겠어요

**Comment by Soogyo-In** [comment]
위 글에대해서 조금 고민해본 결과를 적용한 예제 프로젝트를 만들어 올렸습니다.
README.md에 설명을 작성중이고 내일 스터디 때 까지 정리해가려합니다.
위 내용보다 더 간결히 정리된 것 같아 프로젝트 링크를 첨부하며 이 이슈를 닫습니다. 
[예제 프로젝트](https://github.com/flutterstudygn/archive/tree/master/stream_test)
